// The editor toolbar's icon set — Tabler (the chosen "Outline · Zinc · tabler" look).
// Button/Toggle apply [&_svg]:size-5 so all render at a consistent size.
import {
  TbLock,
  TbLockOpen,
  TbHeading,
  TbUsers,
  TbClock,
  TbTarget,
  TbArrowBackUp,
  TbArrowForwardUp,
  TbAdjustmentsHorizontal,
  TbDots,
  TbRestore,
  TbDeviceFloppy,
  TbDownload,
  TbSettings,
  TbInfoCircle,
  TbChevronDown,
  TbReplace,
  TbVolumeOff,
  TbMusic,
  TbHistory,
  TbPlayerPlayFilled,
  TbHighlight,
  TbTextIncrease,
  TbTextDecrease,
  TbStack2,
} from 'react-icons/tb';

export const I = {
  lock: TbLock,
  unlock: TbLockOpen,
  title: TbHeading,
  speakers: TbUsers,
  timecode: TbClock,
  confidence: TbTarget,
  undo: TbArrowBackUp,
  redo: TbArrowForwardUp,
  view: TbAdjustmentsHorizontal,
  tools: TbDots,
  revert: TbRestore,
  save: TbDeviceFloppy,
  export: TbDownload,
  prefs: TbSettings,
  info: TbInfoCircle,
  chevron: TbChevronDown,
  replace: TbReplace,
  inaudible: TbVolumeOff,
  music: TbMusic,
  restoreTimecodes: TbHistory,
  play: TbPlayerPlayFilled,
  highlight: TbHighlight,
  fontPlus: TbTextIncrease,
  fontMinus: TbTextDecrease,
  presets: TbStack2,
};
